from cStringIO import StringIO
from functools import wraps
from flask import abort
from flask import Response
import flask
from jmsml import Sidc, InvalidSidcLength
from milsymbserver import app
from os.path import join
import xml.etree.ElementTree as ET

ET.register_namespace('', "http://www.w3.org/2000/svg")
NAMESPACE = "{http://www.w3.org/2000/svg}"


def ns_tag(tag_name, namespace=NAMESPACE):
    return "%s%s" % (namespace, tag_name)


def return_svg(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        r = f(*args, **kwargs)
        return Response(r, mimetype='image/svg+xml')

    return decorated_function


@app.route('/')
def index():
    return 'Hello World!'


@app.route('/sidc/<sic>/')
def sic(sic):
    try:
        sidc = Sidc(sic)
    except InvalidSidcLength:
        app.logger.error('Invalid SIDC length')
        abort(404)

    return flask.jsonify(sidc.__dict__)


def merge_svgs(list_of_file_names):
    main_svg = ET.parse(list_of_file_names[0])
    root = main_svg.getroot()
    root.insert(0, ET.Comment("Generated by XXX"))
    for g in root.findall(ns_tag('g')):
        if "id" in g.attrib:
            g.attrib.pop("id")
        if g.get('display', '') == "none":
            root.remove(g)
    for file_name in list_of_file_names[1:]:
        svg = ET.parse(file_name)
        for g in svg.getroot().findall(ns_tag('g')):
            if "id" in g.attrib:
                g.attrib.pop("id")
            if g.get('display', '') != "none":
                root.append(g)
    return main_svg


@app.route('/testsymbol')
@return_svg
def testsymbol():
    svg1 = join(app.config["SVG_PATH"], "Frames/0_001_0.svg")
    svg2 = join(app.config["SVG_PATH"], "Appendices/Air/01110000.svg")
    svg3 = join(app.config["SVG_PATH"], "Appendices/Air\mod2/01042.svg")
    merged_svg = merge_svgs([svg1, svg2, svg3])

    f = StringIO()
    merged_svg.write(f, xml_declaration=True, encoding='utf-8')
    return f.getvalue()